Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/10/2024
Var
// Seção de Declarações das variáveis 
valor1, valor2, aux: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Informe dois valores")
leia (valor1, valor2)

aux <- valor1
valor1 <- valor2
valor2 <- aux

escreval ("valor1: ",valor1,"valor 2:",valor2)

Fimalgoritmo