Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/10/2024
Var
// Seção de Declarações das variáveis 
raio,area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Informe o raio do círculo")
leia (raio)

area <- pi * (raio^2)
escreval("A área do seu círculo com raio de",raio,"é:",area)

Fimalgoritmo