Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/10/2024
Var
numeros: vetor [0..100] de inteiro
i: inteiro
Inicio

para i de 0 ate 5 faca
     escreval ("Informe sua nota")
     leia (numeros[1])
fimpara

Fimalgoritmo